### ISSUE TITLE
black screen

### ISSUE THREAD

**Issue by stanchiang** [iosdevzone/360Video#1]
i ran your code but the screen remains black with the audio playing the background. any ideas?

**Comment by iosdevzone** [comment]
Hi there, what device and version of iOS are you using? What version of Xcode/SDK?

**Comment by stanchiang** [comment]
i'm on a 6s plus, 10.2.0, Xcode 8.2 (8C38)

**Comment by stanchiang** [comment]
actually it's all good. for some reason it works now.
