### ISSUE TITLE
managing device position offset

### ISSUE THREAD

**Issue by stanchiang** [iosdevzone/360Video#2]
i'm toying with a play/pause feature on top of your player where upon going from play to pause the motion tracking pauses as well. before going back from pause to play, the orientation of the phone could change. for example, i could resume watching turned 180 degrees from where i was before.

as a result, upon resuming the device orientation tracking will update the view to show me the content that is 180 degrees from the frame in which i paused.

my goal is to make it such that when i resume playback under my new orientation, i will be able to resume watching from the angle in which i left off and still have the device motion tracking update as i move around while the video is playing again.

i'm struggling to understand how i'd accomplish this as i'm not very experienced thinking in 3d graphics.

how would you offset/update the orientation/quaternion based on the previously paused orientation to solve this use case?

**Comment by iosdevzone** [comment]
I saw you closed this. Sorry I did not have time to look at the code and answer your question. If you have a working solution I would love a pull request to add it to the code.
